spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/db?serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: name
    password: pwd

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # JPA
    properties:
      hibernate:
        format_sql: true
